pipeline:
  name: Employee_Portal
  identifier: Employee_Portal
  projectIdentifier: RanisfirstCICDproject
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Harnessgithubrepo
        repoName: employee-portal
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: GKEConnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Verify Environment
                  identifier: Verify_Environment
                  spec:
                    connectorRef: DockerConnector
                    image: node:20
                    shell: Sh
                    command: |-
                      echo "Current Directory"
                      pwd

                      echo "Listing Files"
                      ls -la

                      echo "Node Version"
                      node -v

                      echo "NPM Version"
                      npm -v
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    connectorRef: DockerConnector
                    image: node:20
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: Unit Test
                  identifier: Unit_Test
                  spec:
                    connectorRef: DockerConnector
                    image: node:20
                    shell: Sh
                    command: npm test || true
              - step:
                  type: Run
                  name: Build Application
                  identifier: Build_Application
                  spec:
                    connectorRef: DockerConnector
                    image: node:20
                    shell: Sh
                    command: npm run build
    - stage:
        name: Docker-Build
        identifier: DockerBuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: GKEConnector
              namespace: harness-delegate-ng
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: DockerConnector
                    repo: chaitrashree22/employee-portal-repo
                    tags:
                      - "1.0"
                    caching: false
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: empportalsvc
            gitBranch: main
          environment:
            environmentRef: Infradev
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: InfraDev
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
